### ISSUE TITLE
bruh emailarchiver was my friends idea

### ISSUE THREAD

**Issue by TechDudie** [Hardwaregore/arkiver#1]

**Comment by TechDudie** [comment]
Not really the cloud is it? Ill be intrsted when you add google drive support

**Comment by TechDudie** [comment]
Sinceim starring this you star emailarchiver

**Comment by Hardwaregore** [comment]
bruh, this is a ripoff of internet archive, not ur email thing

**Comment by TechDudie** [comment]
> Sinceim starring this you star emailarchiver

Just starr it
